Historical data insertion
mojaloop/fraud_risk_management pull request #105
Opened 2020-12-09 06:08 UTC by aaronreynoza

This service inserts historical transactions in a Redis store based on ILP.

2020-12-14 07:52 UTC, johanfol requested changes

2020-12-14 07:52 UTC, johanfol commented on historical-data-store/src/helper.ts
> +  console.log(data);
This must log to Kafka topic ruleEngineLogs - not console - this is very slow.

2020-12-14 07:52 UTC, johanfol commented on historical-data-store/src/redis-client.ts
> +    log(`stored keys are: ${JSON.stringify(keys)}`);
Yeah... no. haha, rather log like the count, or something, not the whole thing?

2020-12-15 04:51 UTC, aaronreynoza commented on historical-data-store/docker-compose.yaml
> +    image: redis
I actually set this up to run redis locally in the meantime. Once we have the k8s cluster running I'm planning to remove all the docker-compose files. we should probably discuss this.

2020-12-15 04:51 UTC, aaronreynoza commented on historical-data-store/package.json
> +  "name": "blocklist-processing-engine",
touche

2020-12-15 05:35 UTC, merged