Add Channel scoring processor
mojaloop/fraud_risk_management pull request #174
Opened 2021-04-19 07:38 UTC by aaronreynoza

2021-04-19 13:59 UTC, johanfol submitted a review, later dismissed

2021-04-19 14:26 UTC, y7usuf requested changes

2021-04-19 14:26 UTC, y7usuf commented on tms-service/tms-service.yml
> +    image: localhost:32000/frm_tms_service:latest
Please rebase or merge the master branch. You'll see deployment and local dev yamls are different. Can you change this file according to the nodejs.template?
(or let's discuss do we need two yaml file? any other solution)
@aaronreynoza @johanfol @JBornman

2021-04-20 14:25 UTC, y7usuf approved these changes

2021-04-20 14:35 UTC, merged