add transaction-aggregation-decisioning processor
mojaloop/fraud_risk_management pull request #183
Opened 2021-05-12 05:56 UTC by aaronreynoza

2021-05-12 05:57 UTC, aaronreynoza commented
TODO:
- Add README
- Add tests
- Integrate with channels processor

2021-05-14 14:57 UTC, joeygoksu approved these changes

2021-05-18 12:14 UTC, joeygoksu approved these changes

2021-05-18 12:15 UTC, joeygoksu approved these changes

2021-05-18 13:23 UTC, johanfol requested changes

2021-05-18 13:23 UTC, johanfol commented on transaction-aggregation-decisioning-processor/src/clients/arangodb.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
please remove ArangoDB as this service doesn't use it. Unnecessary DB connection.

2021-05-18 14:15 UTC, johanfol approved these changes

2021-05-18 15:09 UTC, merged