Testing tool
mojaloop/fraud_risk_management pull request #199
Opened 2021-07-09 13:44 UTC by jonty-esterhuizen

2021-07-12 09:27 UTC, johanfol approved these changes

2021-07-12 10:08 UTC, joeygoksu requested changes

2021-07-12 10:08 UTC, joeygoksu commented on testing tool/grpc-test-example/basic-grpc-server-testing/testing-tool/Readme.md
> +[15:32] Jonty Esterhuizen
We can remove this line

2021-07-12 10:08 UTC, joeygoksu commented on testing tool/grpc-test-example/basic-grpc-server-testing/testing-tool/Readme.md
> +The TMS service is a NodeJs REST-API service that ingests a FRM transaction and validates if it has the correct format.
It's not a REST service. It's a gRPC service that using a single REST endpoint to be activated. (or better explanation)

2021-07-12 10:08 UTC, joeygoksu commented on testing tool/grpc-test-example/basic-grpc-server-testing/testing-tool/hello-world.spec.ts
> +        expect(1).toEqual(1);
Do we really need to check 1=1? If Jest is working the rest of the test should be run.

2021-07-12 10:08 UTC, joeygoksu commented on testing tool/grpc-test-example/basic-grpc-server-testing/testing-tool/hello-world.spec.ts
> +            CustomerServiceClient('127.0.0.1:30043', credentials.createInsecure());
We can add port and URL in Jest environment variables.

2021-07-12 10:08 UTC, joeygoksu commented on testing tool/grpc-test-example/basic-grpc-server-testing/testing-tool/hello-world.spec.ts
> +            expect(callback).toBeNull();
I'm not sure this test is working.

2021-08-04 11:42 UTC, joeygoksu commented
We're moved to the new [organization](https://github.com/actiofrm), there is no need to keep this PR open.
@jonty-esterhuizen informed ✅

2021-08-04 11:42 UTC, closed without merging